name: Node.js Package Create Tag and Release patch

on: workflow_dispatch

jobs:
  build-version-patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: version change
        run: |
          git config --local user.email "rafathaque1997@gmail.com"
          git config --local user.name "rafat97"
          npm version patch --allow-same-version 
          git status 
          git add .
          git commit -m "Push version ${{ steps.tag_version.outputs.new_tag }}"
          git push -force
          
      - run: npm publish 
        env:
         NODE_AUTH_TOKEN: "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"
         
      - name: Package.Json version
        id: pk_version
        run: |
          PACKAGE_JSON_PATH="${1-.}"
          echo "Reading package.json from ${PACKAGE_JSON_PATH}/package.json"
          PACKAGE_VERSION=$(cat ${PACKAGE_JSON_PATH}/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo ::set-output name=current-version::$PACKAGE_VERSION
          
      - name: version 
        run : echo "${{ steps.pk_version.outputs.current-version  }}"
            
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "patch"
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
